name: django_project-local
services:
  db:
    image: postgres:16.2
    restart: always
    env_file:
      - ./.env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.docker
    restart: unless-stopped
volumes:
  postgres_data: